name: Build SunamoRoslyn

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoRoslyn
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoRoslyn/SunamoRoslyn.csproj

    - name: Build
      run: dotnet build SunamoRoslyn/SunamoRoslyn.csproj --configuration Release --no-restore

  test:
    name: Test SunamoRoslyn.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoRoslyn.Tests/SunamoRoslyn.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoRoslyn.Tests/SunamoRoslyn.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoRoslyn.Tests/SunamoRoslyn.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
